sudo: required
services:
  - docker

before_install:
  - docker build -t benjamincusto/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true benjamincusto/react-test npm test -- --coverage

after_success:
  - docker build -t benjamincusto/multi-client ./client
  - docker build -t benjamincusto/multi-nginx ./nginx
  - docker build -t benjamincusto/multi-server ./server
  - docker build -t benjamincusto/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push benjamincusto/multi-client
  - docker push benjamincusto/multi-nginx
  - docker push benjamincusto/multi-server
  - docker push benjamincusto/multi-worker

deploy:
  provider: "elasticbeanstalk"
  region: "eu-west-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-106091765837"
  bucket_path: "docker-multi"
  on:
    branch: "master"
  access_key_id: "${AWS_ACCESS_KEY}"
  secret_access_key: "${AWS_SECRET_KEY}"




